application: qianxuz-explore
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js
  application_readable: true
- url: /fonts
  static_dir: fonts
  application_readable: true
- url: /css
  static_dir: css
  application_readable: true
- url: /templates
  static_dir: templates
  application_readable: true
- url: /static
  static_dir: static
  application_readable: true

- url: .*
  script: main.app

# ... and further down after a bunch of comments
libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: ssl
  version: latest